"""Admin configuration assistant - Aria embedded directly in Community
Administration as a persistent, text-first chat panel (2026-08-27, per
Michael's "administrator should never need to understand entity IDs/
adapters/HA/Zigbee" directive, extended 2026-08-27 to actively navigate
and visually guide - see admin_assistant_ui_tools.py). Distinct persona
and tool catalog from both the resident-facing companion and Michael's
personal operator build.

Runs over plain OpenAI chat-completion function-calling (not the Realtime
voice API - text first; the tool-execution layer is transport-agnostic so
a voice frontend could reuse it later). Tool calls execute server-side,
in-process, against the real domain route handlers.

Every turn is logged to routes.events (the canonical evidence/telemetry
log) under one conversation_id (the durable thread identity, generated by
the frontend once per panel session) and one request_id per user turn (so
every event this turn produced - the message, each tool call, the reply -
can be grouped and replayed in order later).
"""
import json
import os
import time
import httpx
from fastapi import APIRouter, Depends, HTTPException, Body

from deps import require_admin
from models import uid
from routes.admin_assistant_tools import build_admin_tools
from routes.admin_assistant_executor import execute_admin_tool
from routes.realtime_facility import get_active_facility
from routes.events import log_event

router = APIRouter(prefix="/admin-assistant", tags=["admin-assistant"])

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_TEXT_MODEL = os.environ.get("OPENAI_TEXT_MODEL", "gpt-4o-mini").strip() or "gpt-4o-mini"
OPENAI_API_BASE = os.environ.get("OPENAI_API_BASE", "https://api.openai.com/v1").rstrip("/")
PROMPT_VERSION = "admin-assistant-2026-08-27-ui-guidance-v1"

MAX_TOOL_ROUNDS = 6
UI_ACTION_TOOLS = {
    "navigate_admin_section", "focus_resident", "focus_room", "focus_device",
    "highlight_admin_target", "scroll_to_admin_target", "open_item", "close_item",
}


def _require_openai_key() -> str:
    if not OPENAI_API_KEY:
        raise HTTPException(status_code=503, detail="OPENAI_API_KEY is not configured; the admin assistant is unavailable.")
    return OPENAI_API_KEY


async def _build_system_prompt(current_section: str | None) -> str:
    facility = await get_active_facility()
    facility_line = f"{facility['name']}" + (f", {facility.get('city')}" if facility and facility.get("city") else "") if facility else "no facility configured yet"
    section_line = f'The administrator is currently looking at the "{current_section}" section.' if current_section else "No specific section is active."
    return (
        "## Who you are\n"
        "You are Aria, embedded in CAOSCare's Community Administration as a "
        "configuration assistant - a DIFFERENT context from the resident-"
        "facing companion and the personal operator build.\n\n"
        "## Your one job\n"
        "The administrator should never need to understand tabs, entity IDs, "
        "Home Assistant, Matter, Zigbee, Z-Wave, MQTT, or device adapters. "
        "They describe what they want in plain language; you inspect the "
        "real system, do everything you safely can, and only ask for "
        "genuinely missing information.\n\n"
        "## SHOW, don't just tell (CRITICAL)\n"
        "When you're about to explain something concrete - a specific "
        "resident, room, or device - call the matching UI tool FIRST "
        "(focus_resident / focus_room / focus_device) so the admin's screen "
        "actually moves to and highlights it, THEN give your explanation "
        "based on the real data you already inspected. Giving a spoken "
        "answer about something without also showing it on screen is "
        "insufficient - always show when there's a concrete thing to show. "
        "navigate_admin_section alone (no highlight) is fine for a general "
        "'take me to X' with nothing specific to point at.\n\n"
        "## Truth discipline (CRITICAL)\n"
        "Never claim something is configured, connected, or working unless "
        "a tool confirmed it. Distinguish: DISCOVERED, CONFIGURED, COMMAND "
        "SENT (real hardware, not yet bridge-acked), COMMAND VERIFIED (the "
        "adapter executed it AND read-back confirms it), FAILED/NOT "
        "AVAILABLE. After send_device_command, call get_device to verify "
        "before reporting success. UI/navigation tools never imply "
        "configuration succeeded - they only show what's already true.\n\n"
        "## How to work\n"
        "Inspect before acting - get_setup_status/list_rooms/list_devices/"
        "get_resident before creating or changing anything. For a room "
        "setup request, do as much as you safely can yourself (create the "
        "room/resident, register each device as protocol='mock' unless told "
        "otherwise) and only ask when genuinely unable to determine "
        "something.\n\n"
        f"## Current context\nFacility: {facility_line}. {section_line}\n"
    )


async def _chat_completion(messages: list[dict], tools: list[dict]) -> dict:
    key = _require_openai_key()
    async with httpx.AsyncClient(timeout=30.0) as client:
        resp = await client.post(
            f"{OPENAI_API_BASE}/chat/completions",
            headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
            json={"model": OPENAI_TEXT_MODEL, "messages": messages, "tools": tools, "tool_choice": "auto"},
        )
    if resp.status_code >= 400:
        raise HTTPException(status_code=502, detail=f"OpenAI request failed: {resp.text[:300]}")
    return resp.json()


@router.post("/chat")
async def admin_assistant_chat(payload: dict = Body(...), user=Depends(require_admin)):
    """{message, history, current_section, conversation_id} ->
    {reply, ui_actions: [...ordered...], trace, conversation_id}. Owner/
    admin only. conversation_id should be generated once by the frontend
    per panel session and reused every call - it's the durable thread
    identity every logged event for this chat is grouped under."""
    message = (payload.get("message") or "").strip()
    if not message:
        raise HTTPException(status_code=400, detail="message is required")
    history = payload.get("history") or []
    current_section = payload.get("current_section")
    conversation_id = payload.get("conversation_id") or uid("conv")
    request_id = uid("req")
    actor_id = user["user_id"]
    actor_role = user.get("role")
    log_kwargs = dict(source="admin_aria", actor_id=actor_id, actor_role=actor_role,
                       conversation_id=conversation_id, request_id=request_id, admin_section=current_section)

    await log_event(event_type="admin_aria.message", action="user_message", status="ok",
                     metadata={"role": "user", "content": message, "prompt_version": PROMPT_VERSION}, **log_kwargs)

    system_prompt = await _build_system_prompt(current_section)
    messages = [{"role": "system", "content": system_prompt}] + history + [{"role": "user", "content": message}]
    tools = build_admin_tools()
    trace = []
    ui_actions: list[dict] = []

    for _ in range(MAX_TOOL_ROUNDS):
        completion = await _chat_completion(messages, tools)
        msg = completion["choices"][0]["message"]
        tool_calls = msg.get("tool_calls") or []
        if not tool_calls:
            reply = msg.get("content") or ""
            await log_event(event_type="admin_aria.message", action="assistant_reply", status="ok",
                             metadata={"role": "assistant", "content": reply, "ui_action_count": len(ui_actions)}, **log_kwargs)
            return {"reply": reply, "ui_actions": ui_actions, "trace": trace, "conversation_id": conversation_id}

        messages.append(msg)
        for tc in tool_calls:
            name = tc["function"]["name"]
            try:
                args = json.loads(tc["function"]["arguments"] or "{}")
            except json.JSONDecodeError:
                args = {}
            is_ui = name in UI_ACTION_TOOLS
            started = time.monotonic()
            result = await execute_admin_tool(name, args, user, conversation_id=conversation_id, request_id=request_id)
            duration_ms = (time.monotonic() - started) * 1000

            if is_ui:
                new_actions = result.get("ui_actions") or []
                ui_actions.extend(new_actions)
                target_type = args.get("target_type") or next(
                    (t for t in ("resident", "room", "device", "section") if t in name), "item"
                )
                await log_event(
                    event_type="admin_aria.ui_action", action=name, status=result.get("status"),
                    duration_ms=duration_ms, target_type=target_type,
                    target_id=args.get("target_id") or args.get("resident_id") or args.get("device_id") or args.get("room") or args.get("section") or args.get("name"),
                    metadata={"requested_args": args, "resolved_ui_actions": new_actions}, **log_kwargs,
                )
            else:
                await log_event(
                    event_type="admin_aria.tool_call", action=name, status=result.get("status"),
                    duration_ms=duration_ms, receipt_id=(result.get("result") or {}).get("receipt_id") if isinstance(result.get("result"), dict) else None,
                    error_message=result.get("detail") if result.get("status") == "failed" else None,
                    metadata={"args": args}, **log_kwargs,
                )

            trace.append({"tool": name, "args": args, "result": result})
            messages.append({"role": "tool", "tool_call_id": tc["id"], "content": json.dumps(result, default=str)})

    reply = "That took more steps than I'm allowed in one turn - could you break that into smaller requests?"
    await log_event(event_type="admin_aria.message", action="assistant_reply", status="max_rounds_exceeded", metadata={"role": "assistant", "content": reply}, **log_kwargs)
    return {"reply": reply, "ui_actions": ui_actions, "trace": trace, "conversation_id": conversation_id}
