"""Write results/PHASE1_REPORT.md from results/discovery.json + phase1_decisions.json."""
import collections
import json

from lab_common import LAB


def main():
    d = json.loads((LAB / "results/discovery.json").read_text())
    rows = d["rows"]
    dec = {x["id"]: x for x in json.loads((LAB / "results/phase1_decisions.json").read_text())}
    kinds = collections.Counter(r["kind"] for r in rows)
    gates = collections.Counter(g for r in rows for g in r["gates_failed_hard"])
    out = ["# Phase 1 - candidate discovery screen (TEXT STAGE ONLY)", "",
           "Generated by `report_discovery.py` from `discovery.json`. Text screening predicts collision "
           "danger from pronunciations and word/phrase frequency; it does **not** prove acoustic "
           "performance. Methodology: `../METHODOLOGY.md`.", "",
           f"- Candidates screened: **{len(rows)}** ({', '.join(f'{k} {v}' for k, v in kinds.most_common())})",
           f"- Passed the text screen: **{sum(not r['screen_rejected'] for r in rows)}**; "
           f"rejected: **{sum(r['screen_rejected'] for r in rows)}**",
           f"- Corpus: {sum(v['items'] for v in d['corpus_stats'].values() if isinstance(v, dict) and 'items' in v):,} "
           "phonetic items "
           "(CMUdict, wordfreq incl. OpenSubtitles TV/film dialogue, Tatoeba sentences, US Census names, "
           "FDA drug names, authored senior-living vocabulary)",
           "- Hard-gate failures: " + ", ".join(f"{g} {n}" for g, n in gates.most_common()), "",
           "Gates: G0 candidate itself is common; G1 exact common word; G2 near a high-frequency word; "
           "G3 embedded in / contains a common word; G4 near senior-living vocabulary, commands or a "
           "common name (rare names < 1 in 10,000 people are advisory only); G5 distress vocabulary; "
           "G6 a clipped start/end collides; G7 an accent/casual variant collides; G8 speakability.", "",
           "## Advanced to Phase 2 (model training)", "",
           "| Candidate | Phase 1 rank | Measurable | Subjective | Reason |", "|---|---|---|---|---|"]
    for r in rows:
        if dec[r["id"]]["decision"].startswith("advanced"):
            out.append(f"| {r['id']} | {r['rank']} | {r['measurable_composite']} | {r['subjective_composite']} | "
                       f"{dec[r['id']]['reason']} |")
    out += ["", "## Full ranked table", "",
            "Measurable = mean of the text-stage measurable criteria (0-10); Subjective = memorability, "
            "branding, friendliness (0-10, judgement rubric, never used for ranking).", "",
            "| # | Candidate | Kind | Syl | Phon | Measurable | Subjective | Margin | Nearest sound-alikes | "
            "Decision | Reason |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        x = dec[r["id"]]
        out.append(f"| {r['rank']} | {r['id']} | {r['kind']} | {r['syllables']} | {r['phonemes_count']} | "
                   f"{r['measurable_composite']} | {r['subjective_composite']} | {r['collision_margin']} | "
                   f"{', '.join(r['nearest'][:2])} | {x['decision']} | {x['reason']} |")
    (LAB / "results/PHASE1_REPORT.md").write_text("\n".join(out) + "\n")
    print("rows", len(rows))


if __name__ == "__main__":
    main()
