// Resident / family capabilities for the public site. Every card opens a
// panel (CapabilityPanel) with: visuals, the flow (what the resident does,
// what CAOSCare does, what staff see, what happens next), what is built
// today, and what is not yet accepted or still planned.
//
// Status comes from status.js. Flow text for in-development and planned
// capabilities describes the design ("would"), never a working feature.
// All names and rooms in screenshots are sample data.
import { statusOf } from "./status";
import { PHOTOS, SCREENS } from "./visuals";

export const RESIDENT_CAPABILITIES = [
  {
    id: "voice",
    name: "Talk to Aria",
    summary: "Talk with Aria naturally from a chair or bed.",
    limitation: "Proven in the CAOSCare test room. A conversation is started by tapping the room screen; starting by a spoken phrase is still being chosen and tested.",
    visuals: [SCREENS.roomScreen, SCREENS.conversation, PHOTOS.morning],
    flow: {
      does: "Taps \"I just want to talk\" on the room screen and speaks normally.",
      caos: "Knows which resident and room it is, and the name they prefer. Aria answers in her own voice through the room's speakerphone.",
      sees: "Authorized staff can read the conversation in the resident's record, with anything it created.",
      next: "When Aria doesn't know something, she says so rather than guessing.",
    },
    built: "Live spoken conversation with Aria in the test room, saved to the resident record.",
    pending: "Starting a conversation hands-free by a spoken phrase.",
  },
  {
    id: "help",
    name: "Ask for staff help",
    summary: "Ask Aria for help and the request goes to the right department in the resident's own words.",
    visuals: [SCREENS.roomRequests, SCREENS.requestDetail, PHOTOS.caregiver],
    flow: {
      does: "Asks Aria for something, for example help getting to the bathroom.",
      caos: "Turns it into one request for the right department, with the resident's words and priority. A repeat request joins the open one.",
      sees: "Staff see the request on their board and can acknowledge, start and complete it.",
      next: "The resident sees the request on the room screen, and Aria reports its real status when asked.",
    },
    built: "Spoken requests become department requests with the resident's words, shown on the room screen and the staff board.",
    pending: "Staff handling these requests during a real shift has not been accepted.",
  },
  {
    id: "one_press",
    name: "One-press call for help",
    summary: "A single press brings Aria in and puts the call in front of staff.",
    visuals: [SCREENS.roomScreen, SCREENS.staffDashboard],
    flow: {
      does: "Presses the help button on the room screen or a paired pendant.",
      caos: "Opens one assistance call for the room; repeat presses join it. Aria starts talking with the resident.",
      sees: "The call appears on the staff live board until someone acknowledges and closes it.",
      next: "Staff respond in person. Aria doesn't say anyone is on the way unless the record shows it.",
    },
    built: "The press opens one assistance call, starts Aria and shows on the staff live board.",
    pending: "Staff acknowledging and closing calls in normal work, and recovery if the connection drops.",
  },
  {
    id: "rf_pendant",
    name: "Paired pendant",
    summary: "A compatible help pendant paired to a resident and room.",
    limitation: "Proven with one pendant model (319.5 MHz) in the CAOSCare test room. It listens alongside the community's existing call system and never replaces it.",
    visuals: [SCREENS.pendants, SCREENS.staffDashboard],
    flow: {
      does: "Presses their paired pendant.",
      caos: "The room's radio receiver decodes the press and matches it to this resident's pendant.",
      sees: "The pendant list shows the resident, signal, battery and last press; the call appears on the staff board.",
      next: "The press is recorded with its signal and battery condition, so staff can see the pendant is working.",
    },
    built: "Pairing, decoding and signal/battery tracking for one pendant model.",
    pending: "How staff respond to a pendant call is still in development; other pendant models need testing.",
  },
  {
    id: "lighting",
    name: "Lights",
    summary: "Lights on, off or to a brightness by voice or on the room screen.",
    limitation: "Proven with two smart bulbs in the CAOSCare test room. Other light models need testing before installation.",
    visuals: [SCREENS.roomControls, PHOTOS.morning],
    flow: {
      does: "Says \"Aria, set the overhead light to fifty percent\", or uses the light control on the room screen.",
      caos: "Sends the command to that light, then reads back the light's actual state.",
      sees: "The room screen and the device record show the new state.",
      next: "Aria confirms only after the read-back matches; if it doesn't, she says it didn't work.",
    },
    built: "Voice and touch control of real bulbs, confirmed by read-back.",
    pending: "Testing other light models.",
  },
  {
    id: "tv",
    name: "Television",
    summary: "TV power, volume and input by voice or on the room screen.",
    visuals: [SCREENS.roomControls],
    flow: {
      does: "Would say \"Aria, turn on the TV\" or tap the TV control.",
      caos: "Would send the command to the TV and read back what it did.",
      sees: "The device record would show the TV's state.",
      next: "Aria would confirm only what the TV actually reports.",
    },
    built: "The TV control on the room screen and Aria's TV commands (shown here on a demo device).",
    pending: "No real TV is connected yet; the control hardware for the test room still has to be chosen.",
  },
  {
    id: "climate",
    name: "Heating and cooling",
    summary: "Comfort requests turned into a temperature change.",
    visuals: [SCREENS.roomControls],
    flow: {
      does: "Would say \"Aria, I'm cold\" or tap the thermostat control.",
      caos: "Would set the temperature and read back the unit's actual setting.",
      sees: "The device record would show the setting and the room's temperature.",
      next: "Aria would never say the room is warmer just because the setting changed.",
    },
    built: "Temperature commands with read-back, and the thermostat control on the room screen (shown on a demo device).",
    pending: "The test room's air conditioner doesn't stay reliably connected, so no voice temperature change has been confirmed.",
  },
  {
    id: "family_call",
    name: "Family connection",
    summary: "Calling approved family members by name.",
    visuals: [PHOTOS.familyCall],
    flow: {
      does: "Would say \"Aria, call my daughter.\"",
      caos: "Would call only contacts on the resident's approved list.",
      sees: "Family would receive a normal call.",
      next: "Aria would say whether the call actually connected, never guessing.",
    },
    built: "Not built yet.",
    pending: "Planned: calls to approved family contacts, and messages and photos where the resident chooses.",
  },
  {
    id: "phone",
    name: "Phone and calling",
    summary: "A familiar handset, calls within the community, and an answering machine.",
    visuals: [PHOTOS.familyCall],
    flow: {
      does: "Would pick up a simple handset to talk to Aria, or ask Aria to call the front desk or a neighbor.",
      caos: "Would place the call and follow each person's preferences and staff routing.",
      sees: "The person called would receive a normal call; messages would carry the sender's name.",
      next: "Aria would report only calls and messages that really happened.",
    },
    built: "Not built yet; there is no voice calling in CAOSCare today.",
    pending: "Planned: handset and cradle, calls within the community, and a room answering machine.",
  },
  {
    id: "low_vision",
    name: "Built for low vision",
    summary: "Voice first, with a room screen that can be enlarged.",
    visuals: [SCREENS.roomScreen],
    flow: {
      does: "Uses the + and − buttons at the top of the room screen, or asks Aria to make it bigger.",
      caos: "Enlarges the whole room screen, from 50% to 200%.",
      sees: "Nothing needs to go to staff.",
      next: "The size stays set on that room's screen.",
    },
    built: "Screen magnification by touch and by voice.",
    pending: "Not yet tested with residents who have low vision.",
  },
  {
    id: "room_screen",
    name: "The room screen",
    summary: "One simple screen for help, talking to Aria, requests, today's plan and the room.",
    limitation: "Used in the CAOSCare test room. The TV and thermostat shown are demo devices.",
    visuals: [SCREENS.roomScreen, SCREENS.roomToday, SCREENS.roomRequests],
    flow: {
      does: "Sees their name, the time, a large help button and a talk button, with their requests, today's activities and menu, and room controls below.",
      caos: "Fills the screen from the same records Aria and staff use.",
      sees: "Staff update requests, schedules and menus in their own screens; the room screen follows.",
      next: "The TV stays the resident's TV; the screen is a companion, not a menu to learn.",
    },
    built: "The room screen with help, talk, requests, activities, menu and room controls.",
    pending: "Real TV and heating/cooling controls; see those cards.",
  },
  {
    id: "location",
    name: "Building-wide location",
    summary: "Help calls that show where in the building the resident is.",
    visuals: [SCREENS.staffDashboard],
    flow: {
      does: "Would press for help anywhere in the building, wearing an approved device.",
      caos: "Would attach the resident's last known area, only with consent.",
      sees: "Staff would see where to go on the live board.",
      next: "Staff would go to the right place.",
    },
    built: "A live-locations panel on the staff board (shown here with no location data).",
    pending: "No building sensors or wearables are connected.",
  },
  {
    id: "blinds",
    name: "Motorized blinds",
    summary: "Opening and closing blinds by voice.",
    visuals: [PHOTOS.morning],
    flow: {
      does: "Would say \"Aria, open the blinds.\"",
      caos: "Would send the command and read back the result.",
      sees: "The device record would show the blinds' position.",
      next: "Aria would confirm only what the blinds report.",
    },
    built: "Not built yet.",
    pending: "Planned room option.",
  },
  {
    id: "wearables",
    name: "Approved wearables",
    summary: "Supported wearable devices chosen for each community.",
    visuals: [PHOTOS.morning],
    flow: {
      does: "Would wear an approved device from a small supported list.",
      caos: "Would read only the data the resident has consented to share.",
      sees: "Staff and family would see what the resident has agreed to share.",
      next: "What's available depends on the approved device and consent.",
    },
    built: "Not built yet.",
    pending: "Planned: a small approved-device list per community.",
  },
].map((c) => ({ ...c, status: statusOf(c.id) }));

export const RESIDENT_BY_ID = Object.fromEntries(RESIDENT_CAPABILITIES.map((c) => [c.id, c]));
